export const suppliers = [
  {
    id: "silas",
    name: "Silas",
    active: true,
    campus: "UCF",
    locationLabel: "UCF / Sarasota temporary",
    printerTypes: ["FDM"],
    materials: ["PLA"],
    colors: ["black", "white", "gray", "custom"],
    maxBuildVolume: { x: 220, y: 220, z: 250 },
    acceptsRush: true,
    availableNow: true,
    queueLoad: 0,
    trustTier: "founder",
    completedJobs: 0,
    rating: null,
    notes: "Founder supplier. Default supplier while UCF Prints is solo-operated."
  },
  {
    id: "mock-unavailable",
    name: "Unavailable test supplier",
    active: true,
    campus: "UCF",
    locationLabel: "Near main campus",
    printerTypes: ["FDM"],
    materials: ["PLA", "PETG"],
    colors: ["black", "white", "gray", "blue"],
    maxBuildVolume: { x: 250, y: 250, z: 250 },
    acceptsRush: true,
    availableNow: false,
    queueLoad: 5,
    trustTier: "approved",
    completedJobs: 24,
    rating: 4.8,
    notes: "Mock supplier unavailable for matching tests."
  },
  {
    id: "mock-standard-only",
    name: "Standard-only test supplier",
    active: true,
    campus: "UCF",
    locationLabel: "UCF area",
    printerTypes: ["FDM"],
    materials: ["PLA", "PETG"],
    colors: ["black", "white", "gray"],
    maxBuildVolume: { x: 235, y: 235, z: 250 },
    acceptsRush: false,
    availableNow: true,
    queueLoad: 1,
    trustTier: "approved",
    completedJobs: 12,
    rating: 4.6,
    notes: "Mock supplier for testing rush filtering."
  },
  {
    id: "mock-small-volume",
    name: "Small-volume test supplier",
    active: true,
    campus: "UCF",
    locationLabel: "UCF library area",
    printerTypes: ["FDM"],
    materials: ["PLA"],
    colors: ["black"],
    maxBuildVolume: { x: 120, y: 120, z: 120 },
    acceptsRush: true,
    availableNow: true,
    queueLoad: 2,
    trustTier: "trial",
    completedJobs: 3,
    rating: 4.2,
    notes: "Mock supplier for testing material, color, and build-volume filtering."
  }
];
